platform :ios, '11.0'

use_frameworks!

target 'RRoostSDK_Example' do
  pod 'RRoostSDK', :path => '../'

  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'

  target 'RRoostSDK_Tests' do
    inherit! :search_paths

    use_frameworks!
    # Place pods for testing
  end
end
